-- Add up migration script here
CREATE TABLE IF NOT EXISTS Databases (
  id BLOB PRIMARY KEY UNIQUE NOT NULL,
  uri TEXT NOT NULL UNIQUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);